name: question_and_answer_study
description: A new Flutter project.
publish_to: 'none' # Để không publish lên pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Biểu tượng cho iOS
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  url_launcher: ^6.3.0
  dio: ^5.7.0
  path_provider: ^2.1.5
  open_file: ^3.3.2
  permission_handler: ^11.3.0
  file_picker: ^10.1.4
  # Hive database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Phát sinh code cho Hive model
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

  # Quy tắc lint
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/wallpaper.jpg
